### PR TITLE
make run in elysia version 1.1.9

### PR DESCRIPTION
**Pull request by EmmanuelAmodu**

### CODE REVIEW

**Comment by gaurishhs** [comment]
Hey, is this a wip or should i merge it?

**Comment by EmmanuelAmodu** [comment]
> Hey, is this a wip or should i merge it?

Yeah you can merge.

**Comment by AceLikesGhosts** [comment]
Updates on this? ):

**Comment by gaurishhs** [comment]
My bad, I forgot about this

**Comment by gaurishhs** [comment]
Published in v0.0.7

**Pull request merged**
